### ISSUE TITLE
I'm trying to create an admin page, can I use this template commercially? 

### ISSUE THREAD

**Issue by ghost** [york11122/quasar-admin-vue3-typescript#1]

**Comment by york11122** [comment]
No problem, feel free to use it. It's just a practice project, so I hard-coded the user login and data fetching parts. They should be rewritten to suit your specific requirements.

**Comment by ghost** [comment]
Thank you so much!!! 
I want to run it as dev("dev": "quasar dev";) and check the code, but I can't move on because I can't authenticate it on the login screen... How do I get rid of the login authentication part? I've been looking for it, but it's hard

**Comment by york11122** [comment]
I switched the API call of authentication to use fake data from a JSON file. To try it out, you can pull the latest version and run the command 'quasar dev'. I think it is functioning properly now.

**Comment by ghost** [comment]
That was very thoughtful of you! It works fine! I'll keep the source code in mind and do well. Thank you :)
