### ISSUE TITLE
启动报错defineOptions is not defined

### ISSUE THREAD

**Issue by yehoan** [york11122/quasar-admin-vue3-typescript#2]
![image](https://github.com/york11122/quasar-admin-vue3-typescript/assets/22631753/81acebab-fd5b-47ca-a58e-3109e168fc6e)
启动报错了 看了下没有eslint

**Comment by york11122** [comment]
我這邊可以正常運作，
這個主要是 unplugin-vue-define-options (用來定義vue3的component name) 這個套件的問題，
可以檢查看看套件安裝，以及webpack或vite的設定有沒有正確，
這邊的設定是在 quasar.config.js -> vitePlugins
